### ISSUE TITLE
Move report-specific functionality into Report class

### ISSUE THREAD

**Issue by oreoshake** [oreoshake/hackerone-client#20]
`state_change`, `add_comment`, `triage`, `add_report_reference` are all specific to reports yet live in the hodge podge `HackerOne::Client` class. 

This is fine when the library is tiny and with few developers, but it can get out of hand quickly.

There's probably a few opportunities to DRY up the code too.

**Comment by esjee** [comment]
Wouldn't moving this functionality somewhere else cause a breaking change? If so, is that acceptable?

**Comment by oreoshake** [comment]
Maybe we can get away with delegators and deprecation statements but semver does allow for unstable APIs until 1.0.

**Comment by esjee** [comment]
I can look into this once #22 has been merged. Once the helpers introduced in that PR are available, I think resolving this task would be a bit easier.
