### ISSUE TITLE
Optionally assign report to user during report state changes

### ISSUE THREAD

**Issue by oreoshake** [oreoshake/hackerone-client#25]
In order to ensure all reports are assigned to a user, we should opportunistically assign issues upon any state change if the report is unassigned. 

```ruby
def triage(reference, assignee: nil)
def award_bounty(message:, amount:, bonus_amount: nil, assignee: nil)
```

etc. It seems like this would be a common use case and it's entirely optional anyways.

/cc @gregose @brentjo @esjee

**Comment by esjee** [comment]
:+1: :+1: !

This definitely makes sense for triage, and it might make sense for state changes. I'm unsure how useful it is for award_bounty.

For triage: assign to the person who's going to fix it
On state change to resolved: assign to the person who's going to handle the bounty decision, and potential disclosure
On other state changes: remove the assignee (?)

Thoughts?

**Comment by oreoshake** [comment]
I’m not sure about unassigning people or behaving differently for specific states. 

Maybe some config file that states which actions should do what will work but that sound complicated. 

I think the “assign if unassigned” heuristic is pretty universal. An “always assign”/“assign if unassigned” config option could simplify things and support more use cases. 

For us, one person owns things to completion and the assignment never changes. For more complicated workflows, the customization might be too high for any smarts.

**Comment by esjee** [comment]
Starting simple is always good, of course :smile: . The suggested "assign if unassigned" sounds pretty useful. For us as well, there's a group of people that _every_ report gets assigned to. From that point it may get passed on to other groups/individuals. So I'm definitely all for that.

What you said about configs makes me wonder if it would be helpful to add support for hooks. So an `on_state_change` hook. For example:

```ruby
Hackerone::Client.configure do |config|
  config.add_on_state_change_hook -> do |report, from_state, to_state|
    if to_state.triaged? && report.assignee.blank?
      report.assign_to_user 'bob'
    end
  end
end
```

Although honestly, I'm more excited about that because it seems fun to implement. I doubt it will be particularly useful. :grin:

**Comment by oreoshake** [comment]
I like the hook idea. Flexible and easy to document with examples of
workflows.

**Comment by esjee** [comment]
...Maybe we could even do something on the H1 side that allows you to fetch all state changes in a certain timeframe. Something like that would allow you to perform these hooks async on reports that were modified using the regular website. :thinking:

**Comment by oreoshake** [comment]
Do you mean all state changes across multiple reports? If so, that would be
helpful for us. We found many, many unassigned reports and we’re required
to clean that up. The same hook code would work for past and future
reports.

**Comment by esjee** [comment]
Yeah, something along those lines! Not sure what that would look like, though. Maybe an endpoint that returns all activity for all reports on your team, and you can mark activities as "processed"? What do you think?

**Comment by oreoshake** [comment]
I'm not sure we'd leverage the "processed" bit but this seems generally useful as an audit log too.

**Comment by esjee** [comment]
Hmm, looking at this from another way, how would you feel about making some sort of search endpoint?

This endpoint would be able to search for reports with no assignees, for example. You could pull that list every X hours, and loop through the returned reports.

It doesn't have the audit log benefit, but I think this makes everything else a lot easier. Don't have to worry about the processed bit, and it sounds relatively easy to extend.

What do you think?

**Comment by oreoshake** [comment]
I think a search endpoint is an inevitability whether or not it's the best solution to this problem - but it would certainly solve one of the use cases.

**Comment by esjee** [comment]
Would a search endpoint be sufficient to address this specific task?

**Comment by oreoshake** [comment]
I think the search endpoints solves more, but different problems than the one original addressed in the issue. I think the hook system is still worth while.

**Comment by esjee** [comment]
Sorry for the late reply!

To make sure we're on the same page, would a hook system as suggested above (purely client-side) be sufficient for your usecase?

**Comment by oreoshake** [comment]
> To make sure we're on the same page, would a hook system as suggested above (purely client-side) be sufficient for your usecase?

For one of the use cases, going forward, yes. For going back and assigning things historically, a search API would be nice but not necessary.

**Comment by oreoshake** [comment]
Closing this out as incremental activities and state change hooks are 👌
