### ISSUE TITLE
Get all reporters params like page[size] ?

### ISSUE THREAD

**Issue by CR1AT0RS** [oreoshake/hackerone-client#31]
Hey!

I am thinking of adding a pull request to get all reporters. So we need to set  the page[size] =100 and increment page[number]= 1...2...3 etc. till we get zero array size.

I don't see those params for client.reporter am I missing something ?

**Comment by esjee** [comment]
No, you're not missing anything, pagination is an open issue! It's also mentioned in #27, although that one's specific for reports. I think it's possible to construct some kind of generic solution that would work for both endpoints. You might want to check the repo mentioned in #27, which has an existing solution!

**Comment by CR1AT0RS** [comment]
If anyone needs this checkout my latest commits. Closing this issue.
